# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22b974ab80e2a38836859ffff460cb4e7ec8865d0325651c4c2fdc76d289837e7d9728a8f823b7dd45e678bb0daeacaed6309cd1f9ee68d0cf56395d3c9569a

test:
  secret_key_base: 636fbbeec6a454bdf60d40d1bf8d01854fd53209c80cd5cf86b5cfcf918808d0aefddea54cc094abc4fdd46fd0036d8cc27fe9815c111757f8331daf3ff1dde4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
